version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 # this is primary container to run.
    steps:
      - checkout
      - save_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./
      - run:
          name: show message
          command: echo "hello world" # run command
      - run: ls -al ./
      - run: pwd
  test1:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - restore_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo "test 1."
      - run: ls -al ./
      - run: pwd
  test2:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - restore_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo "test 2."
      - run: ls -al ./
      - run: pwd
  test3:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - restore_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo "test 3."
      - run: ls -al ./
      - run: pwd
  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - restore_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: ls -al ./
      # - aws-ecr/build-image:
      #     dockerfile: dockerfiles/Dockerfile
      #     repo: sample-repo
workflows:
  version: 2.1
  test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test3:
          requires:
            - build
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - test1
            - test2
            - test3
      - deploy:
          requires:
            - hold
  # commit:
  #   triggers:
  #     - schedule:
  #         cron: "* * * * *" # 毎週水曜日の14時
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - build
  #     - test1:
  #         requires:
  #           - build
  #     - hold:
  #         type: approval
  #         requires:
  #           - test1
  #     - deploy:
  #         requires:
  #           - hold
