version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 # this is primary container to run.
    steps:
      - checkout
      - run:
          name: show message
          command: echo "hello world" # run command
      - save_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
  build2:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - restore_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo "build 2."

workflow:
  version: 2.1
  wf_name:
    jobs:
      - build
      - build2:
          requires:
            - build
