version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 # this is primary container to run.
    steps:
      - checkout
      - save_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./
      - run:
          name: show message
          command: echo "hello world" # run command
      - run: ls -al ./
      - run: pwd
  build2:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - restore_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo "build 2."
      - run: ls -al ./
      - run: pwd
  build3:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "build 3."
      - run: ls -al ./
      - run: pwd
  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - restore_cache:
          key: ex-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: ls -al ./
      - aws-ecr/build-image:
          dockerfile: dockerfiles/Dockerfile
          repo: sample-repo
workflows:
  version: 2.1
  wf_name:
    jobs:
      - build
      - build2:
          requires:
            - build
      - build3
      - deploy:
          requires:
            - build2
            - build3
